name: Build URL

on:
  push:
    branches:
      - main

jobs:
  build-url:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://script.google.com/macros/s
      SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
      DB_ID: ${{ secrets.DB_ID }}

    steps:
      - name: Build URL
        id: build-url
        run: |
          echo "Building URL..."
          FINAL_URL="$BASE_URL/$DB_ID/exec?path=dishes-table&subscription_key=$SUBSCRIPTION_KEY"
          echo "name=FINAL_URL::$FINAL_URL"
        
      - name: Display URL
        run: echo "Final URL is $FINAL_URL"
